SELECT
EMPLOYEE_ID,FIRST_NAME,LAST_NAME,SALARY,COMMISSION_PCT,(SALARY +
(SALARY * COMMISSION_PCT / 100)) AS TOTAL_SALARY
FROM
OEHR_EMPLOYEES
WHERE
(LAST_NAME = 'Smith' OR LAST_NAME = 'Johnson')
AND SALARY > 5000;
